"""Pydantic schemas for the Workflow Builder API."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# SPEC-005 (Workflow Builder Canvas) — handle vocabulary
# ---------------------------------------------------------------------------

# Source handles allowed by spec.md §4.1 + design.md §2.1 CHECK constraint.
# `success` was removed (constitution §2 — `out` is universal).
SourceHandle = Literal["out", "error", "then", "else", "approved", "rejected", "modified"]
# `in` e o default universal. `condition` aceita tambem `in_a` (CAMPO) e
# `in_b` (VALOR) — ver .claude/rules/canvas-conventions.md.
TargetHandle = Literal["in", "in_a", "in_b"]
MergePolicy = Literal["all", "any"]
ValidationErrorKind = Literal[
    "cycle",
    "fan_in_without_merge",
    "merge_with_zero_inputs",
    "edge_to_nonexistent_handle",
    "unauthorized_tool",
    "max_nodes_exceeded",
    "no_entry_node",
]


# ---------------------------------------------------------------------------
# Shared / Building-block schemas
# ---------------------------------------------------------------------------


class WorkflowStep(BaseModel):
    id: str
    name: str
    type: str  # "tool" | "llm" | "condition" | "action" | "hitl" | "workflow" | "merge"
    tool_name: str | None = None
    prompt: str | None = None
    model: str | None = None  # For type="llm": modelo a usar (default: workflow.default_model)
    workflow_id: str | None = None  # For type="workflow": ID of sub-workflow to execute
    input_mapping: dict[str, str] | None = (
        None  # For type="workflow": map parent output → child input
    )
    config: dict[str, Any] = {}
    next_step: str | None = None
    condition: dict[str, Any] | None = None
    # condition shape: {"field": str, "operator": str, "value": Any, "then": str, "else": str}


class WorkflowStepV2(WorkflowStep):
    """Step extended with canvas coordinates and merge policy (SPEC-005).

    Extends WorkflowStep additively — v1 readers ignore the new fields. position_x/y
    drive the canvas layout (constitution §2 — coordinates are source of truth).
    merge_policy is only set for type='merge'.
    """

    position_x: int = 0
    position_y: int = 0
    merge_policy: MergePolicy | None = None


class WorkflowEdge(BaseModel):
    """Edge between two steps (SPEC-005).

    Identity is the tuple (workflow_id, source_step_id, source_handle,
    target_step_id, target_handle). UUID is internal.
    """

    edge_id: str | None = None  # generated by backend on create
    source_step_id: str
    source_handle: SourceHandle
    target_step_id: str
    target_handle: TargetHandle = "in"


class ValidationError(BaseModel):
    """Single validation finding emitted by validator.py (SPEC-005 Phase B).

    7 kinds defined in spec.md §6.3 / design.md §6.3. `edges` carries the IDs
    involved in a cycle (when kind='cycle'); `step_id` carries the offending
    step (when kind in fan_in/merge/edge/tool/no_entry).
    """

    kind: ValidationErrorKind
    detail: str
    edges: list[str] = Field(default_factory=list)
    step_id: str | None = None


class CronSchedule(BaseModel):
    cron: str
    timezone: str = "America/Sao_Paulo"
    enabled: bool = True


# ---------------------------------------------------------------------------
# Request schemas
# ---------------------------------------------------------------------------


class WorkflowCreate(BaseModel):
    name: str
    description: str = ""
    steps: list[WorkflowStep]
    schedule: CronSchedule | None = None
    client_scope: list[str] = []
    default_model: str = "gemini-flash"
    max_execution_time: int = 300


class WorkflowUpdate(BaseModel):
    name: str | None = None
    description: str | None = None
    steps: list[WorkflowStep] | None = None
    schedule: CronSchedule | None = None
    status: str | None = None
    client_scope: list[str] | None = None
    default_model: str | None = None
    max_execution_time: int | None = None


class RunWorkflowRequest(BaseModel):
    input_overrides: dict[str, Any] = {}
    model_override: str | None = None
    client_id: str | None = None  # override; defaults to the workflow's client_scope[0]


class ResumeRunRequest(BaseModel):
    approved: bool
    feedback: str | None = None
    modifications: dict[str, Any] = {}


# ---------------------------------------------------------------------------
# Response schemas
# ---------------------------------------------------------------------------


class WorkflowRunSummary(BaseModel):
    run_id: str
    status: str
    completed_at: datetime | None = None


class WorkflowResponse(BaseModel):
    id: str
    name: str
    description: str | None
    status: str
    steps_count: int
    schedule_cron: str | None
    schedule_enabled: bool
    last_run: WorkflowRunSummary | None = None
    created_by: str
    created_at: datetime
    updated_at: datetime


class WorkflowDetailResponse(WorkflowResponse):
    definition: dict[str, Any]
    client_scope: list[str]
    default_model: str
    max_execution_time: int


class WorkflowDetailResponseV2(WorkflowDetailResponse):
    """Canvas-aware detail response (SPEC-005).

    Extends V1 with first-class edges and a metadata flag indicating whether
    the workflow has been migrated to the v2 canvas format. `updated_by` is
    surfaced in metadata for FR-WBC-13 concurrent-edit banner.
    """

    edges: list[WorkflowEdge] = Field(default_factory=list)
    canvas_v2_migrated: bool = False
    updated_by: str | None = None


class SetEdgesRequest(BaseModel):
    """Bulk-replace edges of a workflow (SPEC-005 Phase B endpoint)."""

    edges: list[WorkflowEdge]


class ValidateWorkflowResponse(BaseModel):
    errors: list[ValidationError] = Field(default_factory=list)
    warnings: list[ValidationError] = Field(default_factory=list)


class AutoLayoutResponse(BaseModel):
    """Per-step coordinate map returned by auto-layout (SPEC-005)."""

    positions: dict[str, dict[str, int]]
    # positions = { step_id: {"x": int, "y": int} }


class MigrateV2Response(BaseModel):
    migrated: bool
    edges_created: int
    steps_with_position: int


class WorkflowListResponse(BaseModel):
    workflows: list[WorkflowResponse]
    total: int


class RunWorkflowResponse(BaseModel):
    run_id: str
    status: str
    started_at: datetime


class StepLogResponse(BaseModel):
    id: str
    step_id: str
    step_name: str | None
    status: str
    input: dict[str, Any] | None
    output: dict[str, Any] | None
    error: str | None
    duration_ms: int | None
    started_at: datetime | None
    completed_at: datetime | None


class WorkflowRunResponse(BaseModel):
    id: str
    workflow_id: str
    status: str
    trigger: str
    started_at: datetime | None
    completed_at: datetime | None
    error: str | None
    steps_output: dict[str, Any]
    step_logs: list[StepLogResponse] = []


class WorkflowRunListResponse(BaseModel):
    runs: list[WorkflowRunResponse]
    total: int
